# Gradle JVM ayarları ve AndroidX bayrakları.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX zorunlu; eski destek kütüphaneleri kullanılmaz.
android.useAndroidX=true

# R sınıfı modül-bazlı (daha hızlı, daha küçük).
android.nonTransitiveRClass=true

kotlin.code.style=official
